# Generated by Django 2.1.7 on 2019-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
