# Generated by Django 2.1.7 on 2019-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190320_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/tasks'),
        ),
    ]
