# Generated by Django 2.1.7 on 2019-03-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190320_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo',
        ),
        migrations.AddField(
            model_name='task',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='media/tasks'),
        ),
    ]
