# Generated by Django 2.1.7 on 2019-03-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190317_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='user',
            field=models.IntegerField(),
        ),
    ]
