# Generated by Django 2.1.7 on 2019-03-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190317_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLog',
            new_name='TaskDone',
        ),
    ]
